name: floor
description: >
  A supportive SQLite abstraction for your Flutter applications.
  This library is the runtime dependency.
version: 0.7.0
homepage: https://github.com/vitusortner/floor
author: Vitus Ortner <vitusortner.dev@gmail.com>

environment:
  sdk: '>=2.3.0-dev <3.0.0'

dependencies:
  path: ^1.6.2
  math_sqflite:
    git:
      url: https://github.com/rolends1986/sqflite_math.git
      path: sqflite
  floor_annotation:
    git:
      url: https://github.com/rolends1986/floor_math.git
      path: floor_annotation
  meta: ^1.1.6
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^4.1.0
  flutter_test:
    sdk: flutter
